# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quotainXM' do

  pod 'AFNetworking', '~> 4.0.1'
  pod 'SDWebImage'
  pod 'SDCycleScrollView','~> 1.61'
  pod 'MJExtension', '~> 3.2.1'
  pod 'SVProgressHUD'
#  pod  'MBProgressHUD'
  pod 'MJRefresh'
 pod 'Alamofire','=4.9.1'
end
